-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 04-05-2017 a las 04:26:42
-- Versión del servidor: 5.7.14
-- Versión de PHP: 5.6.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `netflix_bd`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_contenidos`
--

CREATE TABLE `tbl_contenidos` (
  `codigo_contenido` int(11) NOT NULL COMMENT 'CAMPO QUE IDENTIFICA DE MANERA UNICA UN CONTENIDO EN ESPECIFICO. ',
  `codigo_tipo_contenido` int(11) NOT NULL COMMENT 'campo que hace referencia al codigo del tipo de contenido que es..',
  `codigo_esrb` int(11) NOT NULL COMMENT 'campo que hace refrencia al codigo esrb del contenido, por ende, el público que esta dirigido.',
  `nombre_contenido` varchar(200) NOT NULL COMMENT 'CAMPO QUE ALMACENA EL NOMBRE DEL CONTENIDO, YA SEA PELICULA, SERIE, NOVELA,ETC...',
  `descripcion_contenido` varchar(4000) NOT NULL COMMENT 'CAMPO QUE ALMACENA LA DESCRIPCION O SINOPSIS DE UN CONTENIDO.',
  `fecha_lanzamiento` date NOT NULL COMMENT 'CAMPO QUE ALMACENA LA FECHA DE LA PUBLICACION O DE LANZAMIENTO DE UN CONTENIDO. ',
  `duracion_contenido` decimal(10,0) NOT NULL COMMENT 'CAMPO QUE ALMACENA LA DURACION DEL CONTENIDO EN LA BASE. ',
  `calificacion_promedio` int(11) DEFAULT NULL COMMENT 'CAMPO QUE ALMACENA LA CALIFICACION PROMEDIO DADA POR LOS USUARIOS. ',
  `url_contenido` varchar(200) NOT NULL COMMENT 'campo que almacena la url o direccion del video del contenido. '
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `tbl_contenidos`
--

INSERT INTO `tbl_contenidos` (`codigo_contenido`, `codigo_tipo_contenido`, `codigo_esrb`, `nombre_contenido`, `descripcion_contenido`, `fecha_lanzamiento`, `duracion_contenido`, `calificacion_promedio`, `url_contenido`) VALUES
(2, 1, 1, 'Dirty Dancing', 'Dirty Dancing: Havana Nights sigue el amoroso romance de la joven pareja Katey (Romola Garai) y Javier (Diego Luna) con el telón de fondo de la revolución cubana en 1958. Katey es una chica estadounidense que vive en Cuba con sus padres y que conoce a Javier, un local. Javier lleva a Katey a un club nocturno donde le enseña a bailar sucio estilo cubano. Los dos se acercan cada vez más, pero cuando Castro toma el relevo, los padres de Katey deciden huir para los Estados Unidos, dejando a Katey para tomar la decisión final', '2014-02-27', '86', 3, 'videos/METRO.mp4'),
(3, 1, 1, 'Kate & Leopold', 'Kate McKay (Meg Ryan) es una ejecutiva moderna del siglo XXI cuya vida está dirigida a triunfar en el mundo empresarial. Leopold (Hugh Jackman), el tercer Duque de Albany, es un caballero soltero y encantador de finales del siglo XIX. Viven en épocas diferentes pero comparten expectativas sociales y profesionales, además de la forma escéptica a la que se enfrentan a sus relaciones sentimentales. Al producirse una rasgadura en el tejido del tiempo, la casualidad hace que Leopold aparezca en la Nueva York de 2002; allí se cruzarán sus caminos y nacerá un curioso romance.', '2001-12-25', '121', 7, 'videos/METRO.mp4'),
(4, 1, 1, 'Mi Amor', 'Cuando Tony es ingresada en un centro de rehabilitación tras sufrir un grave accidente de esquí, empieza a reflexionar sobre la complicada historia de amor que vivió con Georgio. Entre personal médico y analgésicos, se pregunta por qué se aman y cómo fue capaz de ceder ante una pasión tan sofocante como destructiva. Para Tony empieza un duro proceso de reconstrucción a través de un trabajo físico que quizá le permita liberarse de forma definitiva de ese amor pasado que tanto le hizo sufrir. \r\n\r\nMi amor es una apasionada historia de amor dirigida por la directora y actriz Maïwenn (Polisse, Le bal des actrices, Pardonnez-moi) y protagonizada por Vincent Cassel (La Bella y la Bestia), Emmanuelle Bercot (El viaje de Bettie), Louis Garrel (Saint Laurent) e Isild Le Besco (The Good Heart (Un buen corazón)).', '2016-04-15', '130', 6, 'videos/METRO.mp4'),
(5, 1, 1, 'Story of Us', 'Ben Jordan (Bruce Willis) y su esposa Katie (Michelle Pfeiffer) llevan 15 años de matrimonio y aparentemente tienen una vida perfecta. Comparten con sus dos encantadores hijos, Erin (Colleen Rennison) y Josh (Jake Sandvig), un acogedor y cómodo hogar. Sin embargo, cuando los niños no están, la pareja no tienen más remedio que enfrentarse a la cruda realidad de que a estas alturas ninguno de los dos se soporta.\r\n\r\nCuando se acercan las vacaciones escolares, inscriben a sus muchachos en un campamento de verano y, apenas salen del hogar, la pareja comienzan a hacer todos los arreglos necesarios para oficializar su separación. Durante este proceso, cada uno por su cuenta intentará recordar cuáles fueron las razones por las que se enamoraron. ¿Encontrarán motivos suficientes para permanecer juntos?', '1999-11-28', '95', 13, 'videos/METRO.mp4'),
(6, 1, 1, 'Fallen', 'Luce, de 17 años, es una nueva estudiante de Sword & Cross (Espada y Cruz), un internado/reformatorio ubicado en Savannah, Georgia. El novio de Luce murió en circunstancias sospechosas, y ella carga con la culpa de su muerte mientras se mueve por los pocos amistosos pasillos de Sword & Cross, donde cada estudiante parece tener una historia desagradable.\r\n\r\nPero al conocer a Daniel, un guapo estudiante, Luce siente que hay una razón para estar allí - aunque no sabe cuál es. ¿Y el comportamiento frío y distante de Daniel con ella? Realmente es un mecanismo de defensa al que se ha acostumbrado. Daniel es un ángel caído, condenado a enamorarse de la misma chica cada 17 años y verla morir. Y Luce una chica mortal, que tiende a retornar una y otra vez, y que además no tiene ni idea de quién es en realidad.', '2016-11-10', '92', 9, 'videos/METRO.mp4'),
(7, 1, 1, 'La Bella y La Bestia', 'Una joven soñadora y romántica llamada Bella (Emma Watson) vive en una pequeña aldea junto a su padre, un inventor de artilugios, al que algunos consideran un anciano demente. Un día, su padre viaja a una feria para exponer sus inventos, pero se pierde en el camino y acaba en un viejo y misterioso castillo. Buscando cobijo y un lugar donde pasar la noche, el padre de Bella descubre que el señor de ese castillo es una horrible Bestia (Dan Stevens). Cuando se percata de su presencia, la Bestia le deja encerrado entre rejas. \r\nBella, preocupada por su anciano padre, no duda ni un instante en salir en su busca. Cuando encuentra el castillo, Bella decide hacer un intercambio, y quedarse encerrada a cambio de la libertad del anciano. Durante su estancia, la protagonista conocerá a una serie de peculiares personajes que harán que se sienta mucho más cómoda. Además, poco a poco, irá conociendo la Bestia, y se dará cuenta de que, en su interior, hay un gran corazón. La joven se enamora de él, deshaciendo así el antiguo hechizo de la rosa...\r\n', '2017-03-17', '120', 10, 'videos/METRO.mp4'),
(8, 1, 1, 'Experta en Bodas', 'Nadie entiende tanto de amor como Mary Fiore (Jennifer Lopez). Después de todo, es la más prestigiosa organizadora de bodas de San Francisco. Como se especializa en que los sueños de amor se conviertan en realidad, está demasiado ocupada para tener una vida amorosa propia. Mientras celebra el último y más lucrativo contrato -el de la magnate de Internet Fran Donolly (Bridgette Wilson-Sampras)- Mary es rescatada de un choque casi mortal con un camionero en fuga por el Doctor Steve Edison (Matthew McConaughey). Después de pasar juntos la velada más agradable de sus vidas, Mary cree que por fin ha encontrado un motivo para creer en el amor. Bueno, casi. El mundo de Mary cambia de arriba abajo cuando descubre que Steve es en realidad el futuro marido de Fran Donolly, y ella su organizadora de boda. Su carrera y Cupido acaban de chocar.', '2001-01-26', '114', 9, 'videos/METRO.mp4'),
(9, 1, 1, 'La hija del Patron', 'Vital, de 40 años, es jefe de taller en una fábrica textil. Es elegido como “cobaya” por Alix, la hija de 25 años del jefe de la fábrica, que ha venido para hacer un estudio ergonómico. La hija del jefe se rendirá pronto a los encantos de Vital, quien se irá abriendo poco a poco a Alix.', '2016-01-06', '98', 4, 'videos/METRO.mp4'),
(10, 1, 1, 'Moana: Un mar de aventuras', 'Hace 3000 años, la diosa todopoderosa "Te Fiti" fue la que creó todas las islas del océano Pacífico y con eso la humanidad, la flora y la fauna. El semidiós Maui (Dwayne Johnson) quería el Corazón de Te Fiti, el cual creaba las islas. Así que entró en Te Fiti y robó el corazón de la diosa. Pero Maui no era el único que lo deseaba, pues los monstruos marinos también andaban detrás del corazón, tratando de causar el mal y que todas las islas empiecen a desaparecer.', '2016-11-23', '107', 9, 'videos/METRO.mp4'),
(11, 1, 1, 'Gattaca', 'En un futuro no tan lejano, los padres deciden tener hijos con la ayuda de la ingeniería genética para que tengan más salud y mejores oportunidades de conseguir buenos trabajos, ganar más dinero y tener éxito en la vida, frente a la posibilidad de que tengan que competir contra otras personas que fueron mejoradas al nacer, con los adelantos de la ingeniería genética y poder cumplir sus sueños, con todos los dones necesarios para poder participar incluso en la conquista de otros planetas, para ser seleccionados como astronautas y colonos espaciales, deben tener inteligencia superior, alta resistencia física, buena visión y hasta poder prolongar más su vida, al no tener enfermedades genéticas y problemas cardíacos, con la selección de niños más sanos desde el momento de la concepción, los padres seleccionan como quieren tener a sus hijos, desde el sexo del niño, especificar color de ojos, cabello y piel.', '1997-10-24', '106', 10, 'videos/METRO.mp4'),
(12, 1, 1, 'Doctor Strange', 'Después de que Stephen Strange, un aclamado neurocirujano, se vea involucrado en un accidente automovilístico donde sus manos son dañadas, se embarca en un viaje de sanación, donde se encuentra con un ser misterioso llamado Ancestral, quien le enseñará el mundo de las artes místicas.', '2016-10-13', '115', 11, 'videos/METRO.mp4'),
(13, 1, 1, '2001: Odisea del espacio', 'La secuencia inicial del filme se inicia con la imagen de la Tierra ascendiendo sobre la Luna, mientras que el Sol asciende a su vez sobre la Tierra, todos en alineación. En este momento comienza a escucharse la composición musical Así habló Zaratustra de Richard Strauss, la misma que acompaña, en su mayoría, la primera parte de la película titulada El Amanecer del Hombre.', '1968-04-02', '161', 10, 'videos/METRO.mp4'),
(14, 1, 1, 'El hogar de Miss Peregrine para niños peculiares', 'Jacob Portman (Asa Butterfield) es un muchacho de 16 años que ha hecho un gran descubrimiento. Tras haber hallado una serie de misteriosas pistas que se extienden por diferentes mundos y tiempos, el joven emprende un viaje hacia una isla remota para buscar el orfanato donde creció su abuelo Abraham (Terence Stamp). El anciano murió de manera extraña, pero todas sus aventuras han quedado grabadas en la memoria de su nieto. ', '2016-09-27', '127', 8, 'videos/METRO.mp4'),
(15, 1, 1, 'ALIEN 3', 'Tras conseguir escapar con Newt y Bishop de un planeta alienígena, la teniente Ellen Ripley (Sigourney Weaver) recala accidentalmente en Fiorna 161, una remota cárcel galáctica cuyos peligrosos reclusos están absolutamente abandonados a su suerte. (FILMAFFINITY)', '1992-04-01', '115', 7, 'videos/METRO.mp4'),
(16, 1, 1, 'Kung Fu Panda 3', 'Kung Fu Panda 3 es una película de animada de artes marciales y comedia de acción chino-estadounidense, producida por Dreamworks Animation. Está dirigida por Jennifer Yuh Nelson y Alessandro Carloni, escrita por Jonathan Aibel y Glenn Berger, producida por Melissa Cobb, y con la producción ejecutiva de Guillermo del Toro. Es la secuela de la película de 2011 Kung Fu Panda 2 y la tercera entrega de la franquicia de Kung Fu Panda. Fue distribuida por CJ Entertainment en Corea del Sur y la 20th Century Fox en el resto del mundo.', '2016-01-16', '95', 6, 'videos/METRO.mp4'),
(17, 1, 1, 'Cazafantasmas', 'Cazafantasmas es una película de comedia estadounidense de 2016, reboot del clásico film de 1984. El filme está dirigido por Paul Feig, con guion de Kate Dippold y lo protagonizan Melissa McCarthy, Kristen Wiig, Kate McKinnon y Leslie Jones.', '2016-07-09', '116', 4, 'videos/METRO.mp4'),
(18, 1, 1, 'ARQ', 'Atrapados en un laboratorio y en un bucle temporal, una pareja intenta proteger la nueva fuente de energía que podría salvar a la humanidad.', '2016-06-15', '88', 7, 'videos/METRO.mp4'),
(19, 1, 1, 'The Angry Birds', 'The Angry Birds Movie es una película finlandés-estadounidense en 3D de animación por computadora y comedia de acción dirigida por Clay Kaytis y Fergal Reilly, producida por John Cohen y Catherine Winder y escrita por Jon Vitti. ', '2016-05-11', '97', 5, 'videos/METRO.mp4'),
(20, 1, 1, 'Annabelle', 'El film empieza con la misma secuencia vista en El conjuro donde tres jóvenes eran entrevistados por Ed y Lorraine Warren sobre sus experiencias con una muñeca a la que habían llamado Annabelle y que supuestamente estaba poseída.', '2014-10-03', '98', 8, 'videos/METRO.mp4'),
(21, 1, 1, 'Capitán América: Civil War', '"Capitán América: Civil War", de Marvel, empieza donde lo dejó "Vengadores: La Era de Ultrón" ya que Steve Rogers lidera el nuevo equipo de los Vengadores en su incesante tarea de proteger a la humanidad. Pero, después de que otro incidente internacional en el que se ven envueltos los Vengadores produzca daños colaterales, la presión política obliga a poner en marcha un sistema para depurar responsabilidades y a crear un organismo rector que determine cuándo hay que recurrir a los servicios del equipo. El nuevo status que divide a los Vengadores en dos bandos, uno liderado por Steve Rogers y su deseo de mantener la libertad de actuación de los Vengadores a la hora de defender a la humanidad sin interferencias, y otro liderado por Tony Stark y su sorprendente decisión de apoyar los planes y organismos del Gobierno, mientras intentan proteger al mundo de un nuevo malvado.', '2016-05-06', '148', 9, 'videos/METRO.mp4'),
(22, 1, 1, 'Assassin\'s Creed ', 'Assassin\'s Creed cuenta la historia de Callum Lynch (Michael Fassbender), un criminal encerrado en prisión y condenado a ser ejecutado por sus delitos. Pero Lynch recibirá una nueva oportunidad de la organización Abstergo, entidad dirigida por Alan Rikkin (Jeremy Irons). Así, con la ayuda de Sophia Rikkin (Marion Cotillard) y a través de una tecnología revolucionaria que permite rastrear su ADN y desbloquear sus recuerdos genéticos, Lynch experimentará las aventuras de su antepasado Aguilar de Nerha (originalmente llamado Aguilar de Algarrobo), un asesino miembro de la hermandad secreta de los Asesinos y ascendiente suyo que vivió durante la España del siglo XVI, en pleno auge de la Inquisición Española.', '2016-12-21', '115', 9, 'videos/METRO.mp4'),
(23, 1, 1, 'PAN', 'Pan es una película de aventura y fantasía británico-estadounidense de 2015 dirigida por Joe Wright. Está protagonizada por Hugh Jackman, Garrett Hedlund, Rooney Mara, Amanda Seyfried, y Levi Miller. Es una historia original de Peter Pan y el Capitán Garfio, y se estrenó el 9 de octubre de 2015.', '2019-10-09', '112', 7, 'videos/METRO.mp4'),
(24, 1, 1, 'BITE', ' Poco antes de celebrar su boda y durante su despedida de soltera, la joven Casey sufre la picadura de un insecto hasta ahora desconocido. Lo que parece ser un incidente sin importancia pronto empieza a provocar la lenta transformación de su organismo, que no tardan en aflorar y cambiar radicalmente su cuerpo de forma inimaginable.', '2016-08-17', '88', 5, 'videos/METRO.mp4'),
(25, 1, 1, 'Los Pitufos 2', 'Los Pitufos 2 es una película en 3D que fue lanzada el día miércoles 21 de julio del año 2013. Es una secuela de la película de 2011 Los Pitufos, producida por Sony Pictures Animation y distribuida por Columbia Pictures y basada en la serie de historietas homónima creada por Peyo en 1959.', '2013-07-13', '105', 8, 'videos/METRO.mp4'),
(26, 1, 1, 'Buscando A Dory', 'Buscando a Dory (en inglés, Finding Dory) es una película estadounidense en animación 3D por ordenador. Es la secuela de Buscando a Nemo y también está distribuida por Walt Disney Pictures, producida por Pixar y dirigida por Andrew Stanton, que dirigió la película original, y regresó como escritor y director, junto a Angus MacLane como el codirector.2 3 Su estreno fue el 16 de junio de 2016. Volvieron a aparecer algunos personajes de la película anterior, además de Dory están Nemo, Marlin y la pandilla del acuario.', '2016-06-16', '97', 10, 'videos/METRO.mp4'),
(27, 1, 1, 'Lluvia de hamburguesas 2', 'Lluvia de hamburguesas 2: La venganza de las sobras es una película animada dirigida por Cody Cameron y Kris Pearn. Es la secuela de Lluvia de hamburguesas, basado en un popular libro homónimo norteamericano llamado La Lluvia de las albóndigas.', '2013-08-03', '95', 8, 'videos/METRO.mp4'),
(29, 1, 1, 'The Lego Batman Movie', ' es una comedia de aventuras animada por computadora producida en Estados Unidos para estrenarse el 9 de febrero del 2017, spin-off de The Lego Movie. Será dirigida por Chris McKay y escrita por Seth Grahame-Smith, distribuida por Warner Bros. Pictures y contará con las voces protagonistas de Will Arnett, Rosario Dawson, Ralph Fiennes, Michael Cera, Zach Galifianakis y Mariah Carey. Basada principalmente en la línea de construcción de juguetes LEGO.', '2017-02-10', '106', 4, 'videos/METRO.mp4'),
(30, 1, 1, 'Catástrofe en la tierra', 'Con un brillante haz de luz blanco y sin previo aviso, la Luna ha desaparecido. Tras esto, se produce un segundo haz de luz y eso es lo último que todo el mundo recuerda en la Tierra. Once meses más tarde nos encontramos ante un mundo apocalíptico que ha sido arrastrado a un agujero espacio-temporal provocando grandes desastres y colapsando la civilización tal y como la conocemos. Nuestros héroes deberán encontrar una manera de sobrevivir y ponerse a salvo antes de que sea demasiado tarde.', '2016-07-13', '82', 5, 'videos/METRO.mp4'),
(31, 1, 1, 'The Lego Movie 2', 'The Lego Movie (La gran aventura Lego en Hispanoamérica; La Lego película en España) es una comedia de aventuras animada por computadora producida en Estados Unidos1 en 2014. Fue dirigida y coescrita por Phil Lord y Christopher Miller, distribuida por Warner Bros. Pictures y contó con las voces protagonistas de Chris Pratt, Elizabeth Banks, Will Ferrell, Will Arnett, Nick Offerman, Alison Brie, Charlie Day, Liam Neeson y Morgan Freeman. Basada principalmente en la línea de construcción de juguetes LEGO, la película relata la historia de una minifigura Lego ordinaria cuyo destino es salvar el universo Lego de un malvado tirano.', '2014-02-06', '100', 6, 'videos/METRO.mp4'),
(32, 1, 1, 'Sing', 'Sing (¡Canta! en España y Sing: Ven y canta en Hispanoamérica) es una película de animación por computadora del año 2016 producida por Illumination Entertainment. Fue dirigida y escrita por Garth Jennings y co-dirigida por Christophe Lourdelet, y protagoniza las voces de Matthew McConaughey, Reese Witherspoon, Seth MacFarlane, Scarlett Johansson, John C. Reilly, Taron Egerton y Tori Kelly. La trama involucra a un grupo de animales antropomórficos que entran en una competencia de canto, organizada por un koala con la esperanza de salvar su teatro.', '2016-12-21', '108', 9, 'videos/METRO.mp4'),
(33, 1, 1, 'DEAD STORY', ' Anne y Harold son una pareja que se muda a una nueva casa sin saber que era un sitio de asesinatos horrendos (o no, es una pelicula de esas…), la soledad de Anne y su comportamiento extraño hacen que su relación sea muy complicada. cuando Anne descubre una oscura presencia en la casa, ella no tendra ninguna posibilidad de escapar…', '2017-02-15', '102', 8, 'videos/METRO.mp4'),
(34, 1, 1, 'Ovejas y lobos', 'En una lejana y mágica tierra, vive un rebaño de ovejas tranquilamente y sin preocupaciones entre verdes prados y colinas. Pero su vida pastoral se ve interrumpida cuando una manada de lobos decide establecer su campamento en un barranco cercano. \r\n\r\nMientras que las ovejas tratan de encontrar la manera de convivir con sus nuevos vecinos, la manada de lobos se encuentran en plena elección de su próximo líder, tarea que no será nada fácil.', '2016-04-22', '96', 4, 'videos/METRO.mp4'),
(35, 1, 1, 'Demonios 2 ', 'Demonios 2 (título original Dèmoni 2) es una película italiana de 1986 de terror dirigida por Lamberto Bava y co-escrita y producida por Dario Argento. Se trata de la secuela de la película de 1985 Demonios, está protagonizada por David Edwin Knight, Nancy Brilli y Coralina Cataldi-Tassoni, y supuso el debut en el cine a los 10 años de la hija pequeña de Dario Argento, Asia Argento.', '1986-04-03', '91', 7, 'videos/METRO.mp4'),
(36, 1, 1, 'Devil in the Dark', 'Dos hermanos que han pasado años distanciados, deciden realizar un viaje juntos de caza en un extenso bosque. Sin embargo, una vez allí se ven perseguidos por una presencia sobrenatural. Eso hará que tengan que dejar de lado sus diferencias y trabajar juntos para sobrevivir...', '2017-03-07', '96', 8, 'videos/METRO.mp4'),
(37, 1, 1, 'Mi amigo el dragón ', 'n 1977, Pete, un niño de cinco años de edad, está en un viaje por la carretera con sus padres cuando su coche voltea el lado de la carretera tratando de evitar atropellar a un ciervo. Los padres de Pete mueren al instante, pero Pete sobrevive y es perseguido en el bosque por una manada de lobos, sólo para ser rescatado por un dragón con la piel verde, ojos amarillos y enormes alas. Pete nombra al dragón "Elliot" ,ya que de que su libro favorito es sobre un cachorro del mismo nombre. Y se lleva al dragón como una figura paterna.', '2016-08-12', '102', 8, 'videos/METRO.mp4'),
(38, 1, 1, 'Día del atentado', 'Basada en el atentado de la maratón de Boston, Patriots Day cuenta la historia del oficial de policía Ed Davis, que investiga los acontecimientos que se saldaron con la muerte de un terrorista y la detención de otro, ofreciendo una exhaustiva narración de la persecución que se llevó a cabo por toda la ciudad para dar caza a los causantes del atentado. La película está dirigida por Peter Berg (Battleship) y protagonizada por Mark Wahlberg (El jugador, Ted), Lana Condor (X-Men: Apocalipsis) y Michelle Monaghan (Código fuente, la serie de televisión True Detective).', '2016-11-17', '133', 9, 'videos/METRO.mp4'),
(39, 1, 1, 'Tontos y mas Tontos 2', 'Jim Carrey y Jeff Daniels vuelven a encarnar sus famosos papeles de “Dos tontos muy tontos” como Lloyd y Harry en “Dos tontos todavía más tontos”. Los directores de la primera entrega, los hermanos Peter y Bobby Farrelly, llevan a Lloyd y a Harry de viaje para que este último encuentre a la hija que no sabía que tenía y enfrentarse a la responsabilidad que nunca, bajo ningún concepto, debían darle.', '2014-04-03', '110', 10, 'videos/METRO.mp4'),
(40, 1, 1, 'Jurassic World', '22 años después el parque ya es una realidad, llamado Mundo Jurásico. Todo está yendo bien, la gente llega por miles a la isla. Pero la última gran atracción del parque, un dinosaurio carnívoro modificado genéticamente para atraer más visitantes, escapa de su zona de contención y va matando todo a su paso.', '2015-06-09', '124', 9, 'videos/METRO.mp4'),
(41, 1, 1, 'Drácula: La historia jamás contada', 'se niega a una petición del sultán del Imperio otomano Mehmed II (Dominic Cooper): entregar a mil niños para ser convertidos en jenízaros. Eso implica entrar en guerra con el que antaño fuera su amigo y, para evitar una masacre, decide hacer un pacto con un ser diabólico que está oculto en una cueva: dicho ser (Charles Dance) le entregará su poder durante tres días a cambio de que no pruebe la sangre humana. ', '2014-09-30', '92', 8, 'videos/METRO.mp4'),
(42, 1, 1, 'Shelby', 'Shelby es un perro sin dueño que tiene por costumbre fugarse de la perrera cada vez que tiene la oportunidad para desesperación de Doug, el encargado del centro. Durante una de sus escapadas conoce a Jake, un niño que sueña con ser mago.', '2014-11-07', '92', 5, 'videos/METRO.mp4'),
(43, 1, 1, 'GHOST IN THE SHELL: EL ALMA DE LA MÁQUINA', 'Basada en la internacionalmente aclamada saga de ciencia ficción "Ghost in the Shell”. Narra la historia de "Major", un híbrido cyborg-humano femenino único en su especie, que trabaja en operaciones especiales y dirige un grupo operativo de élite denominado Sección 9. Consagrada a detener a los extremistas y criminales más peligrosos, la Sección 9 se enfrenta a un enemigo cuyo objetivo principal consiste en anular los avances de Hanka Robotic en el campo de la cibertecnología. ', '2017-04-03', '107', 10, 'videos/METRO.mp4'),
(44, 1, 3, 'Bajo su Boca (Below Her Mouth) ', 'Jasmine estÃ¡ a punto de casarse, pero una noche cualquiera decide ir a una discoteca y allÃ­ conoce a Dallas, una joven atractiva que llama su atenciÃ³n. Las dos mujeres viven desde entonces una pequeÃ±a aventura de fin de semana que poco a poco se convierte en una apasionada historia de amor. DespuÃ©s de lo que han vivido, sus vidas cambiarÃ¡n para siempre de forma inevitable.', '2016-09-15', '92', 12, 'videos/METRO.mp4');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `tbl_contenidos`
--
ALTER TABLE `tbl_contenidos`
  ADD PRIMARY KEY (`codigo_contenido`),
  ADD KEY `fk_tbl_contenidos_tbl_tipo_contenido1_idx` (`codigo_tipo_contenido`),
  ADD KEY `fk_tbl_contenidos_tbl_esrb1_idx` (`codigo_esrb`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `tbl_contenidos`
--
ALTER TABLE `tbl_contenidos`
  MODIFY `codigo_contenido` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CAMPO QUE IDENTIFICA DE MANERA UNICA UN CONTENIDO EN ESPECIFICO. ', AUTO_INCREMENT=45;
--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `tbl_contenidos`
--
ALTER TABLE `tbl_contenidos`
  ADD CONSTRAINT `fk_tbl_contenidos_tbl_esrb1` FOREIGN KEY (`codigo_esrb`) REFERENCES `tbl_esrb` (`codigo_esrb`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_tbl_contenidos_tbl_tipo_contenido1` FOREIGN KEY (`codigo_tipo_contenido`) REFERENCES `tbl_tipo_contenido` (`codigo_tipo_contenido`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
